//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Startran.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Startran.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adjustable Header 的本地化字符串。
        /// </summary>
        internal static string AdjustableHeader {
            get {
                return ResourceManager.GetString("AdjustableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api: 的本地化字符串。
        /// </summary>
        internal static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api Setting: 的本地化字符串。
        /// </summary>
        internal static string ApiConfigSetting {
            get {
                return ResourceManager.GetString("ApiConfigSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ApiSetting 的本地化字符串。
        /// </summary>
        internal static string ApiSetting {
            get {
                return ResourceManager.GetString("ApiSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoCopy 的本地化字符串。
        /// </summary>
        internal static string AutoCopy {
            get {
                return ResourceManager.GetString("AutoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After setting up, select the &apos;mods&apos; folder and press process 的本地化字符串。
        /// </summary>
        internal static string BeforeTrans {
            get {
                return ResourceManager.GetString("BeforeTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied: {0} 的本地化字符串。
        /// </summary>
        internal static string Copid {
            get {
                return ResourceManager.GetString("Copid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Lang 的本地化字符串。
        /// </summary>
        internal static string DefaultLang {
            get {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory Path: 的本地化字符串。
        /// </summary>
        internal static string DirectoryPath {
            get {
                return ResourceManager.GetString("DirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation prompt text: 的本地化字符串。
        /// </summary>
        internal static string En2Zh {
            get {
                return ResourceManager.GetString("En2Zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Sorting 的本地化字符串。
        /// </summary>
        internal static string EnableSorting {
            get {
                return ResourceManager.GetString("EnableSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find a mod folder that meets the requirements in the target folder 的本地化字符串。
        /// </summary>
        internal static string ErrorFoldersMsg {
            get {
                return ResourceManager.GetString("ErrorFoldersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred: 的本地化字符串。
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while translating 的本地化字符串。
        /// </summary>
        internal static string ErrorTranslating {
            get {
                return ResourceManager.GetString("ErrorTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to get translated result. Please check your settings.\n\n 的本地化字符串。
        /// </summary>
        internal static string ErrorTranslatingMsg {
            get {
                return ResourceManager.GetString("ErrorTranslatingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The changes have not been saved. Would you like to save them? 的本地化字符串。
        /// </summary>
        internal static string IfSaveBeforeClose {
            get {
                return ResourceManager.GetString("IfSaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid directory path. 的本地化字符串。
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lang Key 的本地化字符串。
        /// </summary>
        internal static string LangKey {
            get {
                return ResourceManager.GetString("LangKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Language: 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model: 的本地化字符串。
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods Folder: 的本地化字符串。
        /// </summary>
        internal static string ModsFolder {
            get {
                return ResourceManager.GetString("ModsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Odd/Even Column 的本地化字符串。
        /// </summary>
        internal static string OEColumn {
            get {
                return ResourceManager.GetString("OEColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other: 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} / {1} items {2} pages 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process 的本地化字符串。
        /// </summary>
        internal static string ProcessButton {
            get {
                return ResourceManager.GetString("ProcessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing completed. 的本地化字符串。
        /// </summary>
        internal static string ProcessFinished {
            get {
                return ResourceManager.GetString("ProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proofread 的本地化字符串。
        /// </summary>
        internal static string Proofread {
            get {
                return ResourceManager.GetString("Proofread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectFolder 的本地化字符串。
        /// </summary>
        internal static string SelectFolderButton {
            get {
                return ResourceManager.GetString("SelectFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Border 的本地化字符串。
        /// </summary>
        internal static string ShowBorder {
            get {
                return ResourceManager.GetString("ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Format Error 的本地化字符串。
        /// </summary>
        internal static string ShowFormatError {
            get {
                return ResourceManager.GetString("ShowFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Header 的本地化字符串。
        /// </summary>
        internal static string ShowHeader {
            get {
                return ResourceManager.GetString("ShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Text: 的本地化字符串。
        /// </summary>
        internal static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarTranslator 的本地化字符串。
        /// </summary>
        internal static string StarTranslator {
            get {
                return ResourceManager.GetString("StarTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol 的本地化字符串。
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Lang 的本地化字符串。
        /// </summary>
        internal static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tooltip Mode 的本地化字符串。
        /// </summary>
        internal static string TooltipMode {
            get {
                return ResourceManager.GetString("TooltipMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translate 的本地化字符串。
        /// </summary>
        internal static string TranslateButton {
            get {
                return ResourceManager.GetString("TranslateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translating... 的本地化字符串。
        /// </summary>
        internal static string Translating {
            get {
                return ResourceManager.GetString("Translating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mismatch symbols found. Open proofreading window? 的本地化字符串。
        /// </summary>
        internal static string TranslationMismatch {
            get {
                return ResourceManager.GetString("TranslationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation prompt text: 的本地化字符串。
        /// </summary>
        internal static string TranslationPrompt {
            get {
                return ResourceManager.GetString("TranslationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translation Stopped 的本地化字符串。
        /// </summary>
        internal static string TranslationStopped {
            get {
                return ResourceManager.GetString("TranslationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to translate 的本地化字符串。
        /// </summary>
        internal static string UnableTrans {
            get {
                return ResourceManager.GetString("UnableTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unavailable 的本地化字符串。
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url: 的本地化字符串。
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
